# -*- coding: utf-8 -*-
"""project3_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ejH6md_Yug02CybmzF9bM9-3x9Absp67
"""

"""
Author: Jungmyung Lee

This script loads the BAR_M Z-axis trajectory and five EMG channels,
then visualizes them in two synchronized sets of subplots: the full time
series and a manually selected time window.

Each EMG signal is preprocessed using:
    notch filtering → bandpass filtering → rectification → envelope extraction.

The output consists of 6 full-length plots + 6 sliced-window plots
(12 total), allowing direct comparison between barbell motion and
muscle activation patterns.
"""


import scipy.io as sio
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import butter, filtfilt, iirnotch


# =========================
# Load squat.mat
# =========================
mat = sio.loadmat("/content/squat.mat")
root = mat['qtm_50_c2']

analog = root[0,0]['Analog']
traj   = root[0,0]['Trajectories'][0,0]['Labeled'][0,0]

# 사용할 EMG index들
emg_indices = [3, 4, 5, 6, 8]

# =========================
# Trajectory (BAR_M Z) 준비
# =========================
labels     = traj['Labels'][0]          # (1, N) object array
data       = traj['Data']              # (N, 4, frames)
frame_rate = float(root[0,0]['FrameRate'][0,0])
frames     = int(root[0,0]['Frames'][0,0])

# BAR_M 인덱스 찾기
label_list = [str(l[0]) for l in labels]
bar_idx    = label_list.index("BAR_M")

# Z-axis (index 2)만 사용
bar_z = data[bar_idx, 2, :]                     # (frames,)
t_bar = np.arange(frames) / frame_rate          # 모션캡쳐 시간축


# =========================
# 필터 함수들
# =========================
# Lowpass filter function (4–8 Hz)
def lowpass(cut, fs, order=4):
    nyq = fs / 2
    b, a = butter(order, cut/nyq, btype='low')
    return b, a

# Bandpass filter function
def bandpass(low, high, fs, order=4):
    nyq = fs / 2
    b, a = butter(order, [low/nyq, high/nyq], btype='band')
    return b, a


# =========================
# PLOT (맨 위: BAR_Z, 그 아래 EMG들)
# =========================
n_rows = len(emg_indices) + 1      # 1개는 BAR_Z, 나머지는 EMG
plt.figure(figsize=(15, 16))

# ---------- Row 1: BAR_Z ----------
ax0 = plt.subplot(n_rows, 1, 1)
ax0.plot(t_bar, bar_z, linewidth=1.5)
ax0.set_ylabel("BAR Z", fontsize=12)
ax0.set_title("BAR Z + EMG Rectified + Envelope", fontsize=16)
ax0.grid(True, alpha=0.3)

# 🔥 HERE: BAR_Z에도 0.1초 마이너 눈금 추가
ax0.set_xticks(np.arange(t_bar[0], t_bar[-1], 0.1), minor=True)
ax0.grid(True, which='minor', alpha=0.2)



# ---------- 아래 Row들: EMG ----------
for i, idx in enumerate(emg_indices):

    emg = analog[0, idx]
    raw = emg['Data'][0]
    fs  = float(emg['Frequency'][0,0])

    # ------------ PREPROCESSING -------------
    # 1. Baseline removal
    x = raw - np.mean(raw)

    # 2. 100Hz Notch filter
    b_notch, a_notch = iirnotch(100/(fs/2), 30)
    x = filtfilt(b_notch, a_notch, x)

    # 3. Bandpass 20–450 Hz
    b_bp, a_bp = bandpass(20, 450, fs)
    x_bp = filtfilt(b_bp, a_bp, x)

    # 4. Rectification
    rect = np.abs(x_bp)

    # 5. Envelope using Low-pass Filter (LPF 4–8Hz)
    b_lp, a_lp = lowpass(6, fs)   # 6 Hz 중심
    env = filtfilt(b_lp, a_lp, rect)

    # EMG time vector
    t_emg = np.arange(len(raw)) / fs

    # ------------ PLOT -------------
    ax = plt.subplot(n_rows, 1, i+2)   # +2: 1행은 BAR_Z

    # rectified (blue)
    ax.plot(t_emg, rect, linewidth=0.5, label="Rectified")

    # envelope (orange)
    ax.plot(t_emg, env, linewidth=1.2, label="Envelope")

    # Styling
    ax.set_ylabel(f"EMG {idx}", fontsize=12)
    ax.grid(True, alpha=0.3)

    # 🔥 여기 추가 (0.1 sec 마이너 눈금)
    ax.set_xticks(np.arange(t_emg[0], t_emg[-1], 0.1), minor=True)
    ax.grid(True, which='minor', alpha=0.2)

    # x축 범위를 BAR_Z와 맞춰주고 싶으면 아래 줄 활성화
    ax.set_xlim(t_bar[0], t_bar[-1])

    # Title는 맨 위에서만
    if i == 0:
        pass

    # 마지막 subplot에서만 x축 라벨 표시
    if i == len(emg_indices) - 1:
        ax.set_xlabel("Time (s)", fontsize=12)
    # else:
    #     ax.tick_params(labelbottom=False)
print(label_list)

plt.tight_layout()
plt.show()

# =========================
# EXTRA SUBPLOTS — SLICED 11.5 ~ 15.7 sec
# =========================

#scope

slice_start = 11.5
slice_end   = 15.7

# 새로운 figure 혹은 기존 figure 아래에 추가 가능
plt.figure(figsize=(15, 16))

# ---------- Slice Row 1: BAR_Z ----------
mask_bar = (t_bar >= slice_start) & (t_bar <= slice_end)
bar_z_slice = bar_z[mask_bar]
t_bar_slice = t_bar[mask_bar]

ax0 = plt.subplot(n_rows, 1, 1)
ax0.plot(t_bar_slice, bar_z_slice, linewidth=1.5)
ax0.set_ylabel("BAR Z (slice)", fontsize=12)
ax0.set_title(f"Sliced BAR Z + EMG  ({slice_start} ~ {slice_end} sec)", fontsize=16)
ax0.grid(True, alpha=0.3)
ax0.set_xticks(np.arange(slice_start, slice_end, 0.1), minor=True)
ax0.grid(True, which='minor', alpha=0.2)


# ---------- Slice EMG Rows ----------
for i, idx in enumerate(emg_indices):

    # 다시 EMG raw 불러오기
    emg = analog[0, idx]
    raw = emg['Data'][0]
    fs  = float(emg['Frequency'][0,0])

    # PREPROCESS
    x = raw - np.mean(raw)
    b_notch, a_notch = iirnotch(100/(fs/2), 30)
    x = filtfilt(b_notch, a_notch, x)
    b_bp, a_bp = bandpass(20, 450, fs)
    x_bp = filtfilt(b_bp, a_bp, x)
    rect = np.abs(x_bp)
    b_lp, a_lp = lowpass(6, fs)
    env = filtfilt(b_lp, a_lp, rect)


    # EMG time axis
    t_emg = np.arange(len(raw)) / fs

    # Slice
    mask_emg = (t_emg >= slice_start) & (t_emg <= slice_end)
    t_emg_slice = t_emg[mask_emg]
    rect_slice  = rect[mask_emg]
    env_slice   = env[mask_emg]

    ax = plt.subplot(n_rows, 1, i+2)

    ax.plot(t_emg_slice, rect_slice, linewidth=0.5)
    ax.plot(t_emg_slice, env_slice, linewidth=1.2)
    ax.set_ylabel(f"EMG {idx} (slice)", fontsize=12)
    ax.grid(True, alpha=0.3)

    ax.set_xticks(np.arange(slice_start, slice_end, 0.1), minor=True)
    ax.grid(True, which='minor', alpha=0.2)

    if i == len(emg_indices) - 1:
        ax.set_xlabel("Time (s)", fontsize=12)

plt.tight_layout()
plt.show()
