# -*- coding: utf-8 -*-
"""project3_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1klyokQl7KKsqjzuE6YP-eywnmTMzH_W2
"""

import scipy.io as sio
import numpy as np

def pretty_print(obj, indent=0):
    """
    Author: Jungmyung Lee

    Recursively prints the full structure of a MATLAB .mat file
    in a clear, human-readable format.

    Many biomechanics and motion-capture datasets (e.g., EMG, marker trajectories)
    are stored as MATLAB structs containing nested fields, cell arrays, object arrays,
    and variable-sized numeric matrices. These structures are difficult to inspect
    directly in Python because MATLAB’s hierarchy appears as numpy void/object
    arrays after loading with scipy.io.loadmat().

    This function:
    - detects MATLAB struct elements (numpy void)
    - recursively prints nested fields
    - summarizes large numeric arrays (shape + preview)
    - supports deeply nested biomechanics datasets (e.g., QTM exports)

    Parameters
    ----------
    obj : anything
        A field extracted from scipy.io.loadmat().
    indent : int
        Indentation level for recursive printing.
    """

    space = "  " * indent

    # ---------- CASE 1: MATLAB struct (numpy void) ----------
    if isinstance(obj, np.void):
        fields = obj.dtype.names
        print(f"{space}struct with fields: {fields}")
        for f in fields:
            print(f"{space}- {f}:")
            pretty_print(obj[f], indent + 1)
        return

    # ---------- CASE 2: numpy ndarray ----------
    elif isinstance(obj, np.ndarray):
        # numeric array
        if obj.dtype != object and not obj.dtype.names:
            if obj.size == 1:
                print(f"{space}{obj.flatten()[0]}")
            else:
                print(f"{space}ndarray shape={obj.shape}, dtype={obj.dtype}")
                preview = obj.flatten()[:10]
                print(f"{space}preview (first 10): {preview}")
            return

        # struct array or object array
        print(f"{space}ndarray shape={obj.shape}, dtype={obj.dtype}")
        for idx, element in np.ndenumerate(obj):
            print(f"{space} element {idx}:")
            pretty_print(element, indent + 1)
        return

    # ---------- CASE 3: Python primitive ----------
    else:
        print(f"{space}{obj}")
        return


# ----------- LOAD FILE -----------
mat = sio.loadmat("/content/squat.mat")

# "__" 아닌 키만
keys = [k for k in mat.keys() if not k.startswith("__")]
print("Variables:", keys)

root = mat[keys[0]]
print("\n=== FULL STRUCT & VALUES ===")
pretty_print(root)