# -*- coding: utf-8 -*-
"""project3_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zRT-73N8DfyxvzEC8PzWHZgiHxp9c8bC
"""

"""
Author: Jungmyung Lee

This script loads five EMG channels (indices 3, 4, 5, 6, 8) from a MATLAB motion-capture file
and visualizes each signal with its biomechanics-standard preprocessing steps:
notch filtering → bandpass filtering → rectification → envelope extraction.

Each EMG channel is plotted in its own subplot with both the rectified signal and its low-pass
envelope, and all plots share the same synchronized time axis for easier comparison across muscles.

In total, the script generates six plots (five EMG channels + one shared time-aligned structure),
providing a clear overview of muscle-activation patterns across multiple EMG channels in a single,
well-organized figure.
"""

import scipy.io as sio
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import butter, filtfilt, iirnotch

# =========================
# Load squat.mat
# =========================
mat = sio.loadmat("/content/squat.mat")
root = mat['qtm_50_c2']
analog = root[0,0]['Analog']

# 사용할 EMG index들
emg_indices = [3, 4, 5, 6, 8]

# Lowpass filter function (4–8 Hz)
def lowpass(cut, fs, order=4):
    nyq = fs / 2
    b, a = butter(order, cut/nyq, btype='low')
    return b, a


# =========================
# Bandpass filter function
# =========================
def bandpass(low, high, fs, order=4):
    nyq = fs / 2
    b, a = butter(order, [low/nyq, high/nyq], btype='band')
    return b, a

# =========================
# PLOT
# =========================
plt.figure(figsize=(15, 14))

for i, idx in enumerate(emg_indices):

    emg = analog[0, idx]
    raw = emg['Data'][0]
    fs = float(emg['Frequency'][0,0])

    # ------------ PREPROCESSING -------------
    # 1. Baseline removal
    x = raw - np.mean(raw)

    # 2. 100Hz Notch filter
    b_notch, a_notch = iirnotch(100/(fs/2), 30)
    x = filtfilt(b_notch, a_notch, x)

    # 3. Bandpass 20–450 Hz
    b_bp, a_bp = bandpass(20, 450, fs)
    x_bp = filtfilt(b_bp, a_bp, x)

    # 4. Rectification
    rect = np.abs(x_bp)

    # 5. Envelope using Low-pass Filter (LPF 4–8Hz)
    b_lp, a_lp = lowpass(6, fs)   # 6 Hz 중심, 4~8Hz 범위에 해당
    env = filtfilt(b_lp, a_lp, rect)


    # Time vector
    t = np.arange(len(raw)) / fs

    # ------------ PLOT -------------
    ax = plt.subplot(len(emg_indices), 1, i+1)

    # rectified (blue)
    ax.plot(t, rect, color='tab:blue', linewidth=0.5, label="Rectified")

    # envelope (orange)
    ax.plot(t, env, color='tab:orange', linewidth=1.2, label="Envelope")

    # Styling
    ax.set_ylabel(f"EMG {idx}", fontsize=12)
    ax.grid(True, alpha=0.3)

    # 🔥 여기 추가 (0.1 sec 마이너 눈금)
    ax.set_xticks(np.arange(t_emg[0], t_emg[-1], 0.1), minor=True)
    ax.grid(True, which='minor', alpha=0.2)

    # Title only on top
    if i == 0:
        ax.set_title("EMG Rectified + Envelope (Channels 3, 4, 5, 6, 8)", fontsize=16)

    # 모든 subplot에 x축 숫자 표시
    ax.set_xlabel("Time (s)", fontsize=12)

plt.tight_layout()
plt.show()