"""
Author: Jungmyung Lee

This script implements a Streamlit-based web interface for pose-based
basketball shooting analysis. (AI Basketball Shooting Coach)

Users can upload a shooting video, trigger the analysis pipeline,
and receive a predicted shooting score along with explainable,
body-part-level feedback generated by the trained model.
"""


# app.py
import streamlit as st
import tempfile
import os

from infer_single import infer

# ===============================
# Page Config
# ===============================
st.set_page_config(
    page_title="AI Basketball Shooting Coach",
    page_icon="🏀",
    layout="centered"
)

# ===============================
# Title & Description
# ===============================
st.title("🏀 AI Basketball Shooting Coach")
st.write(
    "Upload a basketball shooting video and "
    "**an AI coach will analyze your shooting form, assign a score, "
    "and explain which body mechanics need improvement.**"
)

st.divider()

# ===============================
# Video Upload
# ===============================
uploaded_file = st.file_uploader(
    "📤 Upload shooting video (mp4)",
    type=["mp4", "mov", "avi"]
)

if uploaded_file is not None:
    # Save uploaded video as a temporary file
    with tempfile.NamedTemporaryFile(delete=False, suffix=".mp4") as tmp:
        tmp.write(uploaded_file.read())
        video_path = tmp.name

    st.video(video_path)
    st.divider()

    # ===============================
    # Inference Button
    # ===============================
    if st.button("🧠 Analyze My Shooting Form"):
        with st.spinner("Analyzing shooting mechanics..."):
            result = infer(video_path)

        # -------------------------------
        # temp file cleanup (안정화)
        # -------------------------------
        try:
            os.remove(video_path)
        except OSError:
            pass

        # ===============================
        # Error Handling
        # ===============================
        if "error" in result:
            st.error(result["error"])
        else:
            # -------------------------------
            # 안전한 key 접근 (방어 코드)
            # -------------------------------
            score = result.get("score", None)
            details = result.get("details", {})
            feedback = result.get("feedback", [])

            # ===============================
            # Score Section
            # ===============================
            st.subheader("📊 Shooting Form Score")
            if score is not None:
                st.metric("Overall Score", f"{score} / 100")
            else:
                st.metric("Overall Score", "N/A")

            st.divider()

            # ===============================
            # SHAP-based Joint Contribution
            # ===============================
            st.subheader("🦾 Joint Contribution Breakdown (Explainable AI)")

            elbow_val = float(details.get("elbow", 0.0))
            wrist_val = float(details.get("wrist", 0.0))
            hip_val   = float(details.get("hip", 0.0))

            total = elbow_val + wrist_val + hip_val + 1e-6

            elbow_ratio = elbow_val / total
            wrist_ratio = wrist_val / total
            hip_ratio   = hip_val / total

            st.write("**Elbow Contribution**")
            st.progress(float(elbow_ratio))
            st.caption(f"{elbow_ratio * 100:.1f}% of total performance penalty")

            st.write("**Wrist Contribution**")
            st.progress(float(wrist_ratio))
            st.caption(f"{wrist_ratio * 100:.1f}% of total performance penalty")

            st.write("**Lower-body Contribution**")
            st.progress(float(hip_ratio))
            st.caption(f"{hip_ratio * 100:.1f}% of total performance penalty")

            st.divider()

            # ===============================
            # AI Coach Feedback
            # ===============================
            st.subheader("💬 AI Coach Feedback")

            if len(feedback) == 0:
                st.write("• No specific feedback available for this shot.")
            else:
                for msg in feedback:
                    st.write("• " + msg)

            st.success("Analysis complete! 🏀")
